options:
  logging: CLOUD_LOGGING_ONLY  # Sends logs to Cloud Logging

steps:
  # Remove cached dependencies to avoid issues
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: bash
    args:
      - '-c'
      - 'rm -rf node_modules package-lock.json && npm cache clean --force'

  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '--legacy-peer-deps']

  # Ensure permissions are correct for node_modules (only if needed)
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: bash
    args:
      - '-c'
      - 'chmod -R 777 node_modules'

  # Build the React project
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'react-app'
      - '--image'
      - 'gcr.io/micro-shift-449410-a1/react-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/micro-shift-449410-a1/react-app'
